server:
  port: 8082
spring:
  datasource:
    hikari:
      connection-timeout: 60000
      idle-timeout: 60000
      max-lifetime: 1800000
      maximum-pool-size: 10
    password: ${db_password}
    url: ${db_url}
    username: ${db_username}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
---
spring:
  config:
    activate:
      on-profile:
      - development
      
server:
  port: 8083